### ISSUE TITLE
position 6 => capture the king

### ISSUE THREAD

**Issue by Wishmaster7** [TytiX/ng-hnefatafl#10]
load position 6 => this move should capture the king (instead : error in console, attackers continue playing)
![image](https://user-images.githubusercontent.com/49399072/65513959-9f66da00-dedc-11e9-9aec-ccc1e4366192.png)

**Comment by Wishmaster7** [comment]
same wrong behavior with position 5

**Comment by Wishmaster7** [comment]
same wrong behavior with position 4

**Comment by TytiX** [comment]
the game end has not been implemented yet. Error should be replace by the win/loose message.
